version: "3.9"

services:

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: 12345678
      DOCKER_INFLUXDB_INIT_ORG: TestBeam_org
      DOCKER_INFLUXDB_INIT_BUCKET: Fers_bucket_abs
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: Kr73sktQb-QMH3rCNCPuMdgh8d3HSdb8vseQ6Jp8PukdVNcDkttpWaSG3rZ8JrWn6TMt4K8v3i0nx5OBhtXFSg==

  grafana:
    image: grafana/grafana:11.6.14
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb

  python:
    build: ./python
    container_name: daq-python
    volumes:
      - ./data:/data
      - ./python:/app
    depends_on:
      - influxdb
    stdin_open: true
    tty: true


volumes:
  influx-data:
  grafana-data:
